### ISSUE TITLE
ver.0.9.0 のプラグイン追加機能

### ISSUE THREAD

**Issue by DBCTRADO** [DBCTRADO/TVTest#11]
ver.0.9.0 で、プラグインのインターフェースに以下の機能追加を考えています。
- DirectShow 関係の通知
  - フィルタグラフ構築・破棄時の通知
- スタイル設定の取得
  - TVTest.style.ini の設定の取得
  - 各種フォント設定の取得
- テーマの描画
  - 現在の配色設定を使用して背景の描画
- EPG 蓄積状況の取得

他に欲しい機能がありましたら教えてください。

**Comment by j0hn---** [comment]
プログラミングなどなにもわからないの素人ですが
今更追加機能のリクエストは可能でしょうか？
もしよろしければ、番組表から視聴予約（右クリックメニュー等）ができるとありがたいのですが
実現可能でしょうか？

**Comment by DBCTRADO** [comment]
以前そのような機能を考えてはいましたが、ちゃんと作ろうとすると時間が掛かりますので実現していませんでした。
将来的な課題としてはあると思いますが、すぐにはできないと思います。
番組表からの視聴予約自体は、TTRecなどのプラグインで可能なものがあるようです。

**Comment by j0hn---** [comment]
早速ご返答頂き、ありがとうございます。
TTRecプラグインの使用で概ね期待通りの動作になりました。

**Comment by xtne6f** [comment]
設定→録画→保存プラグインの第一候補の設定ボタンがグレーアウトします。
`CRecordOptions::DlgProc()`の`EnableDlgItem(hDlg,IDC_RECORDOPTIONS_WRITEPLUGINSETTING,Sel>0);`
はたぶん`Sel+1`です。

**Comment by DBCTRADO** [comment]
ありがとうございます。
cc6e16cf49b3a5a70069b79e5bc32080bd6a08dc で修正しました。

**Comment by DBCTRADO** [comment]
450adc0311caf555182ba2499f1ab31386064843 で ver.0.9.0 のプラグイン仕様確定。
