### ISSUE TITLE
CStatusViewに対するWM_RBUTTONDBLCLKの扱い

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTest#15]
今のところCStatusViewに対するWM_RBUTTONDBLCLKメッセージは無視されるようですが、例えばWM_RBUTTONDOWNと同じ扱いにするなどで、これを取得できるように仕様変更できないでしょうか。
右ダブルクリック自体は使わないのですが、プラグインインターフェースから利用するときに右押下のメッセージが間引かれてしまうため、連打がとても鈍くなります。

**Comment by DBCTRADO** [comment]
右ダブルクリックに対応したいと思います。
ついでに中央ボタンやホイールも対応した方がいいですね。

**Comment by xtne6f** [comment]
ありがとうございます。
実のところ右ダブルクリックというものを利用したアプリケーションを知らないので
個人的には操作性統一のため対応しないのも手だと思ったりします。
// APIの対称性とか設計ポリシーとかあるので、あくまで個人的な意見

**Comment by DBCTRADO** [comment]
私も個人的には右ダブルクリック操作というのはしないのですが、
右ダブルクリックに何か機能を割り当てるといのもあり得なくはないと思いますので、
区別できた方がいいかなと思っています。

**Comment by DBCTRADO** [comment]
以下のコミットで対応しました。

71a084e3a3cf172af4b3e40de3f12952c6f96053 プラグインのステータス項目のマウス操作の通知に右ダブルクリックと中央ボタンを追加
e6f5c03447afc699211b735d443bee0c8875466d プラグインのステータス項目のマウス操作の通知にホイール操作を追加

**Comment by xtne6f** [comment]
ありがとうございます。右ダブルクリック通知、動作確認しました。
(表題解決のためIssue閉じます)
