### ISSUE TITLE
"ウィンドウ枠：細くする"を選択した場合マウスの反応位置がズレる

### ISSUE THREAD

**Issue by FX8350** [DBCTRADO/TVTest#16]
ウィンドウ枠：細くする　を選択するとマウスがウィンドウサイズ変更モード(⇔とか↕)になる位置が境界ではなくえらく内側にズレます。
通常と"なくす"は特に問題ありませんでした。
WIndows 8.1で確認しました。

**Comment by DBCTRADO** [comment]
確認してみましたが、「細くする」と「なくす」で特に差は見られませんでした。
えらく内側というのはどの程度でしょうか。
境界ではサイズ変更のカーソルにならず、内側でないとカーソルが変わらないということでしょうか。

**Comment by FX8350** [comment]
書き方が悪かったです。境界では当然反応するのですが、それ以上に内側でも反応してるように感じます
それともう一度確認してみたところ「なくす」の方でも同じ感じでした
文字だけだと上手く説明できないので画像するとこんな感じです
![2](https://cloud.githubusercontent.com/assets/10481430/5695961/b9a6555e-99fd-11e4-88e1-72590f751289.PNG)

**Comment by xtne6f** [comment]
横ヤリですみませんが、CMainWindow::ChildHookProc()で子ウインドウに送られたWM_NCHITTESTをフックしてる部分が本来やりたい事と違っているからだと思います。
つまり、FrameWidthとFrameHeightの値です。

**Comment by DBCTRADO** [comment]
詳しくありがとうございます。
枠を「細くする」と「なくす」にした場合、システムから取得したサイズ変更枠の幅の分だけサイズ変更できるようにしています。
具体的には GetSystemMetrics(SM_CXSIZEFRAME / SM_CYSIZEFRAME) で取得していますが、
この値がOSやテーマ・DWMの有効/無効で大分変わってくるのと、
exeファイルのサブシステムの設定によっても変わってくるようですね ( http://support.microsoft.com/kb/2584604/ja )。
XPでは現在のまま、XP以外では SystemParametersInfo(SPI_GETNONCLIENTMETRICS) で取得した
NONCLIENTMETRICS の iBorderWidth + iPaddedBorderWidth を使うのがいいかも知れません。

**Comment by xtne6f** [comment]
たしかにリンカオプションに`/SUBSYSTEM:Windows,6.0`でSM_CXSIZEFRAMEは4になりました(Win8.1)
// 全体で8になるようにSM_CXPADDEDBORDERも4になった
XPは元々サイズ変更枠が4ぐらいで狭かった気がするので、Win7や8で変更枠が広くなるのは(デフォルトのデザイン的に)仕方ないのですね。
サイズ変更できるようにするのは良いですね。

**Comment by FX8350** [comment]
なるほど、別にズレていたりフォントで判断してる訳ではなく単純にWindows 8.1だとサイズ変更枠の幅がデカいという訳ですね…
仰る通り`/SUBSYSTEM:Windows`の`6.0`に指定すれば見たと同じような幅になったのでしばらくこれでビルドします。
ありがとうございました。

**Comment by DBCTRADO** [comment]
1022c372f7d4cd6d9feb349c83042ac0dc651773 でサイズ変更枠の幅のデフォルト値を NONCLIENTMETRICS から取得するようにしました。
また、スタイルファイルでも設定可能にしました。

**Comment by FX8350** [comment]
ありがとうございます。スタイルファイルで微調整可能なのは大変ありがたいです。
