### ISSUE TITLE
イベントリレー情報の取得

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTest#20]
プラグインインタフェースのMESSAGE_GETEPGEVENTINFOで得られるEventGroupListにイベントリレー情報(イベントグループ記述子の種別2または4)を含めてもらえませんでしょうか。
関連部分はCEventManager::OnSection()のm_EventGroupListのあたりで、現状セクションの最初の記述子だけ受け取っているように思われます。
m_EventGroupListは本体で利用していないぽいので純粋にプラグインへの便宜になってしまいますが、余裕があればご一考ください。

**Comment by DBCTRADO** [comment]
対応したいと思います。

**Comment by DBCTRADO** [comment]
aa888993b2fad5c9953c14a5168ee251e0b497a6 で対応しました。

**Comment by xtne6f** [comment]
素早い対応感謝です。
とりあえず種別4について動作確認しました。
