### ISSUE TITLE
チャンネル名の文字化け

### ISSUE THREAD

**Issue by k725** [DBCTRADO/TVTest#21]
Issue #6 で報告した問題の続きです。

![default](https://cloud.githubusercontent.com/assets/3895461/6898794/16c56f1a-d737-11e4-8db1-f167248ab097.png)

現時点で最新の 4548ba7cc08b3288220f0e27d2542e1e5b714d09 をビルドして使用しています。
``.\epgdata`` を削除した上で試したのですが、添付の画像のようになってしまいます。

また、非Unicodeアプリケーションの言語が日本語以外になっていると番組表のタイトルバー文字化けするのですが、これは解決可能でしょうか…。

![default](https://cloud.githubusercontent.com/assets/3895461/6898878/ae0c34f8-d737-11e4-836c-39da6f97c026.png)

普通に日本語にしていれば発生しない問題ですが、気になったので報告させていただきました…。

**Comment by DBCTRADO** [comment]
試してみましたが問題なく表示され、現象が再現しませんでした。

**Comment by DBCTRADO** [comment]
他のプログラムのタイトルバーの日本語は正常に表示されていますか？
また、フォント関係のプログラムを利用している場合、無効にしてみるとどうでしょうか？

**Comment by k725** [comment]
お忙しい中返信有り難うございます。
フォント関係のプログラムはあまり関係ないとは思いますが、MacTypeをインストールして利用しています。
一旦無効化しても変わりませんでした。

![japanese](https://cloud.githubusercontent.com/assets/3895461/6921239/8450ed8a-d7fe-11e4-8ff6-795b29a9caa9.png)

今、もう一度一からコンパイルしなおしたのですが、特に変わりません…。
(コンパイルする際、Shift-JISだとコンパイルできないので全てのファイルを一度UTF-16 LEに変換しています。)

**Comment by DBCTRADO** [comment]
現象の起こるロケールは何でしょうか？

ProgramGuide.cpp の6813行目
`::SetWindowText(m_hwnd,pszFileName);`
の前に
`TRACE(L"EPG Title=%s\n",pszFileName);`
のようなものを入れるなどして、pszFileName の内容が正常か化けているか試してもらえますでしょうか。
\# 違う話ですが、pszFileName という名前は間違いですね。

**Comment by k725** [comment]
問題が発生したロケールはen-USです。
後者に関しましては ``TRACE`` や ``OutputDebugString`` を使用して指定された位置にコードを挿入してみましたが、デバッガに表示されませんでした…。

なお、開発環境が入っていないWin8.1 x64 日本語版のマシンで、
試してみましたが文字化けは発生せずに表示されました。
(問題が発生したマシンでビルドしたTVTestです。)

**Comment by DBCTRADO** [comment]
こちらも「英語 (米国)」で試しましたが問題ありませんでした。
ブレークポイントを設定して pszFileName の内容を見てみるとどうでしょうか？

**Comment by k725** [comment]
``TRACE`` や ``OutputDebugString`` だとデバッガで文字化けしてしまうので ``Messagebox`` で試した所、文字化けせずに表示されました。

![eqamcg](https://cloud.githubusercontent.com/assets/3895461/6965725/99baf436-d98e-11e4-986c-c80b1a0f2699.png)

(もしかするとWindows側の問題…？ )

**Comment by DBCTRADO** [comment]
SetWindowText 内で化けているのだと思いますが、通常考えられませんし、原因はちょっと分かりませんね。

**Comment by k725** [comment]
ふと気づいたのですが ``notepad.exe`` を引数無しで起動するとタイトルバーは化けませんが、
引数を指定して(e.g. ``notepad.exe "C:\test.txt"``)起動すると文字化けしてしまいます。

他の環境では試していないので不明なのですが、もしかすると私のWindowsの問題かもしれません…。
長々となってしまい申し訳ないですが、明日違う環境で試してみたいと思います…。

![hmm](https://cloud.githubusercontent.com/assets/3895461/6983791/0bfbc27c-da5d-11e4-96ee-9fbc81e4c8b2.png)

**Comment by k725** [comment]
本日ロケール変更をした別のマシンで試した所、症状が再現出来ませんでした。
システム側の可能性が高いので、時間のあるときに原因を調べてみたいと思います。

なので一旦Closeとさせて頂きます。
長々となってしまい申し訳ありませんでした。
