### ISSUE TITLE
一部のロケールでチャンネル設定ファイルが破損する

### ISSUE THREAD

**Issue by k725** [DBCTRADO/TVTest#22]
お世話になっております。

先日の件とは別件ですが、バグらしきものを発見したので報告させて頂きます。

ロケールがen-US になっている環境で、チャンネルスキャンを行うとファイルが中途半端に書き込まれます。
サーバ(ja-JP)上のTVTestでチャンネルスキャンを行うとShift-JISで問題なく書き込まれますが、
クライアント(en-US)のTVTestでチャンネルスキャンを行うとUTF-16で途中までしか書き込まれません。

なおチャンネルスキャンをした直後はスキャンできたチャンネルがすべて表示され、(下記の例で言えば)フジテレビ等が視聴可能ですが、
一度でも終了させると、ファイルが途中までしか書き込まれていないため見れません。
(なので、現状はサーバ上のTVTestでスキャンしたデータをクライアントに持ってきて使用しています。)

破損しているファイル (クライアントでチャンネルスキャン)

	; TVTest チャンネル設定ファイル
	; 名称,チューニング空間,チャンネル,リモコン番号,サービスタイプ,サービスID,ネットワークID,TSID,状態
	;#SPACE(0,地上D)
	ＮＨＫ総合１・東京,0,14,1,1,1024,32736,32736,1
	ＮＨＫ総合２・東京,0,14,1,1,1025,32736,32736,0
	ＮＨＫ携帯Ｇ・東京,0,14,1,192,1408,32736,32736,0
	ＮＨＫＥテレ１東京,0,13,2,1,1032,32737,32737,1
	ＮＨＫＥテレ２東京,0,13,2,1,1033,32737,32737,0
	ＮＨＫＥテレ３東京,0,13,2,1,1034,32737,32737,0
	ＮＨＫ携帯２,0,13,2,192,1416,32737,32737,0
	ｔｖｋ１,0,5,3,1,24632,32375,32375,1
	ｔｖｋ,0,5,3,192,25016,32375,32375,0
	日テレ１,0,12,4,1,1040,32738,32738,1
	日テレ２,0,12,4,1,1041,32738,32738,0
	日本テレビ,0,12,4,192,1424,32738,32738,0
	テレビ朝日,0,11,5,1,1064,32741,32741,1
	テレビ朝日,0,11,5,1,1065,32741,32741,0
	テレビ朝日,0,11,5,1,1066,32741,32741,0
	テレビ朝日,0,11,5,192,1448,32741,32741,0
	ＴＢＳ１,0,9,6,1,1048,32739,32739,1
	ＴＢＳ２,0,9,6,1,1049,32739,327

正常なファイル (サーバでチャンネルスキャン)

	; TVTest チャンネル設定ファイル
	; 名称,チューニング空間,チャンネル,リモコン番号,サービスタイプ,サービスID,ネットワークID,TSID,状態
	;#SPACE(0,地デジ(UHF))
	ＮＨＫ総合１・東京,0,14,1,1,1024,32736,32736,1
	ＮＨＫ総合２・東京,0,14,1,1,1025,32736,32736,0
	ＮＨＫ携帯Ｇ・東京,0,14,1,192,1408,32736,32736,0
	ＮＨＫＥテレ１東京,0,13,2,1,1032,32737,32737,1
	ＮＨＫＥテレ２東京,0,13,2,1,1033,32737,32737,0
	ＮＨＫＥテレ３東京,0,13,2,1,1034,32737,32737,0
	ＮＨＫ携帯２,0,13,2,192,1416,32737,32737,0
	ｔｖｋ１,0,5,3,1,24632,32375,32375,1
	ｔｖｋ,0,5,3,192,25016,32375,32375,0
	日テレ１,0,12,4,1,1040,32738,32738,1
	日テレ２,0,12,4,1,1041,32738,32738,0
	日本テレビ,0,12,4,192,1424,32738,32738,0
	テレビ朝日,0,11,5,1,1064,32741,32741,1
	テレビ朝日,0,11,5,1,1065,32741,32741,0
	テレビ朝日,0,11,5,1,1066,32741,32741,0
	テレビ朝日,0,11,5,192,1448,32741,32741,0
	ＴＢＳ１,0,9,6,1,1048,32739,32739,1
	ＴＢＳ２,0,9,6,1,1049,32739,32739,0
	ＴＢＳ,0,9,6,192,1432,32739,32739,0
	テレビ東京1,0,10,7,1,1072,32742,32742,1
	テレビ東京2,0,10,7,1,1073,32742,32742,0
	テレビ東京3,0,10,7,1,1074,32742,32742,0
	テレビ東京携帯,0,10,7,192,1456,32742,32742,0
	フジテレビ,0,8,8,1,1056,32740,32740,1
	フジテレビ,0,8,8,1,1057,32740,32740,0
	フジテレビ,0,8,8,1,1058,32740,32740,0
	フジテレビ,0,8,8,192,1440,32740,32740,0
	ＴＯＫＹＯ　ＭＸ１,0,7,9,1,23608,32391,32391,1
	ＴＯＫＹＯ　ＭＸ２,0,7,9,1,23609,32391,32391,0
	ＭＸワンセグ１,0,7,9,192,23992,32391,32391,0
	ＭＸワンセグ２,0,7,9,192,23993,32391,32391,0
	Ｊ：ＣＯＭテレビ,0,0,10,1,23656,32397,32397,1
	Ｊ：ＣＯＭテレビ,0,0,10,1,23657,32397,32397,0
	Ｊ：ＣＯＭチャンネル,0,27,11,1,24696,32383,32383,1
	Ｊ：ＣＯＭチャンネル,0,27,11,1,24697,32383,32383,0
	放送大学１,0,1,12,1,1088,32744,32744,1
	放送大学２,0,1,12,1,1089,32744,32744,0
	放送大学３,0,1,12,1,1090,32744,32744,0

当方の環境です。

Server

 - Windows Server 2012 R2 DC x64
 - Spinel_ver3.6.1.1
 - BonDriver_PT- ST（人柱版３）

Client

 - Windows 8.1 WMC x64 
 - TVTest efdc31b29d9cc5ecdce426512c20f8f661bc5555
 - BonDriver_Spinel_ver3.5.3.0

お手数をお掛けしますが、お時間の有るときに確認していただけると幸いです。

**Comment by DBCTRADO** [comment]
e01aba15311d3b1d2de99cad45eca0139b431db7 で修正しました。

**Comment by k725** [comment]
わざわざお忙しい中バグ修正本当にありがとうございました。
