### ISSUE TITLE
Windows 10で使用した際のバージョン画面

### ISSUE THREAD

**Issue by k725** [DBCTRADO/TVTest#24]
いつもコミットありがとうございます。

動作に影響はしていないので優先度低めな問題ですが、
Windows 10だとバージョン画面が一部写真のようにおかしくなるみたいです。
気になったのでIssueに投げさせていただきました。

0356b9527a0cf148fe6e9061339c690878d67c59 + Windows 10 Pro build 10532 で確認しています。

![1](https://cloud.githubusercontent.com/assets/3895461/9657156/8d2af36a-5279-11e5-9a7b-42e24a3cef65.png)

**Comment by DBCTRADO** [comment]
Windows 10 で DwmExtendFrameIntoClientArea の動作がおかしいようなので使わないようにしました。

**Comment by k725** [comment]
お忙しい中ご対応ありがとうございました！
