### ISSUE TITLE
音声出力の拡張

### ISSUE THREAD

**Issue by 9060** [DBCTRADO/TVTest#25]
パスツルー音声出力をAACだけでなくAC3にも

**Comment by DBCTRADO** [comment]
音声がAC3のTSに対応するということか、音声をAC3にエンコードするということでしょうか。
いずれにしてもあまり必要性が感じられません。

**Comment by DBCTRADO** [comment]
042bce616706df6b62e2052133d41a7584b8cc53 でAC3音声に対応。
