### ISSUE TITLE
CPanel::SetPanelTheme()のバグ?

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTest#26]
設定→テーマ/配色を切り替えていくと一部のテーマ(Metroなど)でテーマが動的に適用されなくなるので、なんでかなと探ってみたところ、CPanel::SetPanelTheme()のGetTitleRectは正しくはGetClientRectではないでしょうか?

**Comment by DBCTRADO** [comment]
報告ありがとうございます。
288c2ceb9ac126204174176ec7c1808adf6c24b0 で修正しました。

**Comment by xtne6f** [comment]
修正確認しました。ありがとうございます。
