### ISSUE TITLE
コーディングスタイルを統一する

### ISSUE THREAD

**Issue by DBCTRADO** [DBCTRADO/TVTest#27]
ファイルによってコーディングスタイルが異なっているのを統一する。

**Comment by xtne6f** [comment]
（コーディングスタイル絡みということで…）
TVTestPlugin.hのTVTEST_OFFSETOFについて、C/C++標準のoffsetofマクロがあればそちらにできないでしょうか。
```
#ifdef offsetof
#define TVTEST_OFFSETOF offsetof
#else
...
```
というのも、`((size_t)((BYTE*)&((type*)0)->member-(BYTE*)(type*)0))` の表現はgccで定数にならずエラーになるためです。MinGWなどで開発に便利なので、コンパイル可能だと嬉しいです。
また、`interface IGraphBuilder`ですが、interfaceはWIN32_LEAN_AND_MEANしたwindows.hで定義されないので、`struct IGraphBuilder`とできないでしょうか。

**Comment by DBCTRADO** [comment]
修正しました。

**Comment by xtne6f** [comment]
問題なさそうです。ありがとうございます。
