### ISSUE TITLE
Tvtest.hのTVTEST_Hの#endifが正しく閉じられていない

### ISSUE THREAD

**Issue by moorejones** [DBCTRADO/TVTest#28]
VS2015Communityエディションで昨日開発ブランチのビルドをしていましたが、最後の#endifが正しくないようで、ビルドに失敗します。TVTEST_Hを除去するとAPPNAME_Aがない、アイコンが見つからない等々出てきます。

**Comment by DBCTRADO** [comment]
#endif の対応に特に問題はないと思います。
ビルドに失敗するというのの具体的な内容を教えてください。

**Comment by moorejones** [comment]
Windows 10 Insider Preview Build 14279上のVisual Studio 2015 Community Editionでビルドしています。
Windows Updateでパッチは最新の状態、Windows SDKも導入済みの環境です。Debug/Releaseどちらでもビルド試してみましたが、同じエラーでビルドが停止しました。

ソースはDevelopブランチをそのままZIPでダウンロードしたものです。ダウンロードしたものをそのままビルドするとソースコード内で使われている文字コードの影響で別の警告が出るため、UTF-8に全て変換したものについてもビルドしましたが、同じエラーでビルド停止しました。ビルドログを添付しますので見て頂けますでしょうか。
[TVTestBuildlog_utf8_rel.txt](https://github.com/DBCTRADO/TVTest/files/170146/TVTestBuildlog_utf8_rel.txt)
[TVTestBuildlog_Errors_uft8_rel.txt](https://github.com/DBCTRADO/TVTest/files/170147/TVTestBuildlog_Errors_uft8_rel.txt)
[TVTestBuildlog.txt](https://github.com/DBCTRADO/TVTest/files/170148/TVTestBuildlog.txt)
[TVTestBuildlog_Errors.txt](https://github.com/DBCTRADO/TVTest/files/170149/TVTestBuildlog_Errors.txt)
[TVTestBuildlog_utf8.txt](https://github.com/DBCTRADO/TVTest/files/170145/TVTestBuildlog_utf8.txt)
[TVTestBuildlog_Errors_uft8.txt](https://github.com/DBCTRADO/TVTest/files/170144/TVTestBuildlog_Errors_uft8.txt)

**Comment by DBCTRADO** [comment]
Shift_JIS のダメ文字でエラーになっているように見えます。

> ユニバーサル文字名 '\u3067' によって表示されている文字は、現在のコード ページ (1252) で表示できません

のような出力があるので、何らかの理由でコードページが Shift_JIS (CP932) になっていないのが原因のようです。
ソースを UTF-8 にした場合では、リソース以外は問題なくコンパイルできているのではないでしょうか。

> エラー	RC1020	unexpected '#endif'	TVTest	D:\src\TVTest-develop\src\TVTest.h	80

これも TVTest.rc の文字コードが正しく解釈されていないために出ているのではないかと思います。
TVTest.rc でコードページを明示するようにしてみましたが、Shift_JIS のままコンパイルしてエラーが出るようであれば、 `code_page(932)` を `code_page(65001)` に書き換えて UTF-8 で保存し直してみたらどうでしょうか。

dbghelp.h で警告が出るのは Windows SDK のバグです。

**Comment by moorejones** [comment]
ありがとうございます。

ソースファイルを全てUTF-8に変換後、TVTest.rcを指示通りcode_page(65001)に変更して試してみましたがやはり同じエラーでビルド停止するため、#ifndef TVTEST_と対応する #endifを削除してリトライしてみました。

加えて、https://blogs.msdn.microsoft.com/jpvsblog/2015/08/03/visual-studio-2015-shift-jis/
にある対策を65001に書き換えて関連するプロジェクトファイルに付け加えました。

添付のビルドログに詳細は出ていますが、リソースクリプトがうまく読み込めていない様です。

こちらの環境がInsiderビルドに日本語言語パックを適用した状態なのでダメ文字については日本語版を用意した状態で再度確認する必要がありそうです。

プロジェクトにメニューからリソースを新規作成→追加した時のファイルも添付しますが、オリジナルの記述とは異なるのでこちらはダメ文字を解消してから改良してみようと思います。

リソーススクリプトのデフォルトの文字コードはUTF-16LEでした。ソースコードはUTF-8なのにリソーススクリプトスクリプトはUTF-16LEだなんてややこしいですね。。。準備が出来次第また書き込みします。

[TVTestBuildlog_Errors_uft8.txt](https://github.com/DBCTRADO/TVTest/files/170719/TVTestBuildlog_Errors_uft8.txt)
[TVTestBuildlog_utf8_rel.txt](https://github.com/DBCTRADO/TVTest/files/170720/TVTestBuildlog_utf8_rel.txt)
![rc_2247onvs2015](https://cloud.githubusercontent.com/assets/17695536/13726490/94ecf18c-e90c-11e5-99db-707dc7787146.png)
[resource1.txt](https://github.com/DBCTRADO/TVTest/files/170728/resource1.txt)
[resource.txt](https://github.com/DBCTRADO/TVTest/files/170730/resource.txt)
[Resource_rc.txt](https://github.com/DBCTRADO/TVTest/files/170729/Resource_rc.txt)

**Comment by moorejones** [comment]
大分遅くなりましたが続報です。

今回はWindows 10 Pro 日本語版+2016/03迄のWindows Update + VS 2015 CE Update 2の環境でビルドしたところ、無事完了できました。

OSの言語以外に大きな差異はないので、文字コードの取り扱いに原因がありそうです。

とりあえず問題はなさそうなので一旦クローズさせていただきます。ありがとうございました！
