### ISSUE TITLE
タスクバーの文字列も個別にカスタマイズ

### ISSUE THREAD

**Issue by j0hn---** [DBCTRADO/TVTest#29]
タイトルバーとは別にタスクバー文字列もカスタマイズできるようにして頂く事は可能でしょうか？
例えば、タイトルバー上では、「サービス名／番組名」という文字列。
タスクバー上では、「番組名」という文字列のみ。というように設定したいのですが...。
もし可能ならご検討頂ければ幸いです。
よろしくお願い致します。

**Comment by DBCTRADO** [comment]
そうしたい理由はなんでしょうか。
基本的にWindowsの仕様として「タイトルバーの文字列＝タスクバーの文字列」なので、できるとしてもトリッキーなコードになってくるため、相応のメリットが無ければあまり気が進みません。

**Comment by j0hn---** [comment]
お忙しいところ早速ご返答頂きありがとうございます。
デュアルモニタのセカンダリ側に最大化表示させてタイトルバーを表示した状態で使用していますが
タイトルバーの文字が（左寄せのせいもあって）一見確認しづらい事があるので、
プライマリ側タスクバーの限られたスペースで必要な情報だけ表示できればと安易に考えてしまいました。
申し訳ありません。

**Comment by DBCTRADO** [comment]
とんでもないです。要望は歓迎します。
考えてみたら、独自タイトルバーにしている時であれば割と簡単なので、それ限定であれば実装するかも知れません。
最小化時も別に設定できるようにするなど、他の場合も合わせて考えたいですね。
いずれにしてもマイナーな設定なので、隠し設定的な扱いになると思いますが。

**Comment by j0hn---** [comment]
ご検討頂いてありがとうございます！
お手数おかけしますが、もしも気が向きましたらよろしくお願い致します。

**Comment by DBCTRADO** [comment]
設定機能を実装してみました。
TVTest.ini の [Settings] に以下の設定を追加してください。

- MinimizedTitleTextFormat (最小化時のタイトル)
- MaximizedTitleTextFormat (最大化時のタイトル)
- TaskbarTitleTextFormat (タスクバーのタイトル。独自タイトルバー使用時のみ)

**Comment by j0hn---** [comment]
早速の実装ありがとうございます！
非常に助かりました。
ありがとうございました！

**Comment by DBCTRADO** [comment]
後で設定ダイアログに載せる可能性もありますが、設定はできるようにしたので閉めます。
