### ISSUE TITLE
ウィンドウがスクリーンをまたがる状態でフルスクリーンにすると残骸が残る

### ISSUE THREAD

**Issue by Xanardi** [DBCTRADO/TVTest#36]
TVTestをウィンドウモードの状態にしてマルチディスプレイの間をまたがる配置にし，フルスクリーンモードに変更すると，ウィンドウモードの残骸がディスプレイに残ってしまう。

**Comment by DBCTRADO** [comment]
フルスクリーンにした時も、元のウィンドウはそのまま残る仕様です。
特にウィンドウを隠す必要もないかと思い、そのようになっています。
