### ISSUE TITLE
チューナー空間 1 以降のチャンネルデータのみを取得した状態でBonDriverの読み込み（初期化）に失敗するとフリーズ（強制終了）する。

### ISSUE THREAD

**Issue by tkmsst** [DBCTRADO/TVTest#42]
以下の手順で再現可能です。

1. TVTest\BonDriverのフォルダに、BonDriver_BDAS.dll（BonDriver_PT3-Sでも可なはず）を格納する。
2. TVTestを起動し、BonDriverの検索フォルダの設定、およびデフォルトのBonDriverを前回起動時のものに設定し、「CSのみ」チャンネルスキャンする。
3. いったん終了してから起動し、CSのチャンネルデータが正常に読み込まれ、正常に視聴できていることを確認する。
（この際、BSはチャンネルデータは取得していないため、BonDriver側で設定された表示になっている）
4. TVTestを終了させ、BonDriver_BDAS.dll（BonDriver_PT3-S）を削除してから、再起動する。
5. BonDriverが読み込めませんとエラーが表示されるので、OKを押す。
6. この時点でTVTestの画面左下のチューナーボタンを押して、他のBonDriverを選択しようとしてもメニューが表示されない。
7. 数秒後、TVTestが強制終了する。

本来、BonDriverのチューナー空間は 0 からの連続した番号でなければならないところ、CSのみ取得したため、TVTestのチャンネルファイル（.ch）には 1 のみ存在することになります。これが不具合の原因だと思われます。
極めて特殊な状況だとは思いますが、念のため報告させていただきます。

環境：
Windows 10 x64
BonDriver_BDAS.dll Ver.1.03
Visual Studio 2017
Commit:470eb68158fd06021e01386ad9397e9f0f94d278

**Comment by DBCTRADO** [comment]
報告ありがとうございます。
チャンネルファイルにないチューニング空間のチャンネルは BonDriver から取得したものを使うようにしていましたが、
BonDriver が読み込めていない場合はそれが無いため、NULL ポインタアクセスで落ちていました。
修正したいと思います。

**Comment by tkmsst** [comment]
早速のご返答とご解説ありがとうございます。
よろしくお願いいたします。

**Comment by tkmsst** [comment]
修正ありがとうございました。
