### ISSUE TITLE
Spinel経由で衛星チューナーを開くと強制終了する

### ISSUE THREAD

**Issue by timarupopoka** [DBCTRADO/TVTest#45]
まっさらな状態のTVTestに、BonDriver_SpinelとTVTestVideoDecoderを入れて起動し、
BonDriver_Spinelから衛星チューナーを開くとTVTestが強制終了します。
地上波チューナーは正常に開けます。
またSpinelを経由せずBonDriver_PT-Sを直接開いた場合も問題ありませんでした。
ec6b9ba03c3b86c5b448754ccf575858c26193f2 以降のTVTestで発生するようです。
a871a5a8b6faa808df16ecfa7eba639adf943384 では問題ありませんでした。

環境
Windows10 1903
TVTestVideoDecoder 0.3.0
Spinel 3.6.1.1
BonDriver_Spinel 3.5.3.0

**Comment by DBCTRADO** [comment]
それらしい箇所を修正しました。

**Comment by timarupopoka** [comment]
チューナーを正常に開けることを確認しました。
ありがとうございました。
