### ISSUE TITLE
CS視聴中にSpinel経由でチャンネル変更が発生すると再生が止まる

### ISSUE THREAD

**Issue by timarupopoka** [DBCTRADO/TVTest#46]
状況としてはSpinel経由で2つのTVTestがチャンネル争奪をしているような場面です。
再現手順は以下の通りです(単一のホスト内で再現可能)。

1. BonDriver_SpinelでCSを視聴できるよう設定したTVTestを2つ用意する(A,Bとする)
2. 両者ともSpinelの排他制御は無効にしておく(RequireExclusiveChannelControl = 0)
3. Aの[BonDriver設定]で[初期チャンネル]を[前回終了時のチャンネル]にする
4. Aで任意の衛星チャンネルを選局したのちTVTestを終了する
5. Bを起動し「Aと同じチューナー」で「Aで選局したサービス以外のCSチャンネル」を選局する
6. Aを起動して先程と同じチューナーを開く

排他制御が無効なため、ここでBの画面はAと同じサービス内のチャンネルに
自動的に切り替わり、再生が継続されることが期待されますが止まってしまいます。
これはAがチューナーを開くタイミングでのみ発生するようで、
A,Bともに既に視聴中の状態で、いずれかのチャンネルを切り替えたときには
もう一方もそれに追随するという期待通りの動作になりました。
また地デジやBSでも期待通りの動作になりました。
本件は0.7.23からの移行作業中に気づいたもので、以下のバージョンで確認しました。

0.7.23(x86) OK
0.8.0(x86) NG
0.8.2(x64) NG
0.9.0(x64) NG
0.10.0(x64) a871a5a8b6faa808df16ecfa7eba639adf943384 NG

実際はAのバージョンは何でもよく、Bのバージョンに依存するようです。
またSpinelの代わりにBonDriverProxyを使用してみましたが改善されませんでした。

環境
Windows10 1903
Spinel 3.6.1.1
BonDriver_Spinel 3.5.3.0
BonDriverProxy 1.1.6.5

**Comment by DBCTRADO** [comment]
CSのサービスは勝手に切り替わらない仕様に変更した記憶があります。
CSの物理チャンネル内の各サービスはそれぞれに関連性があるわけではなく、たまたま同じ物理チャンネルに入っているというだけなので、自動的に追従するのは不自然との判断です。
地上波やBSの場合、追従させるには先頭のサービスを選択すればいいですが、CSは「先頭のサービス」といったものに特に意味は無いため、どのサービスを選択すればいいかというのが分かりません。

**Comment by timarupopoka** [comment]
そのような仕様になったのですね。
動きが少ない番組（将棋など）で止まっていることにしばらく気づかなかったり、
あと珍しい使い方かもしれませんが、チャンネルはなんでもいいのでBGMのように
とにかく流しっぱなしにしておきたいときなどに少し不便に感じました。
また追従した先でたまたま面白そうな番組をやっていたなんてこともあり、
以前の仕様を結構気に入っているので、勉強して改造に挑戦したいと思います。

**Comment by timarupopoka** [comment]
追記
AppCore.cpp の ServiceSel.FollowViewableService に true を指定(2箇所)することで0.7.23相当の挙動にできました。
