### ISSUE TITLE
Snap not working

### ISSUE THREAD

**Issue by gdassieu** [DBCTRADO/TVTest#50]
Hi,

First, thanks for making TVTest. It's wonderful!

I just found a bug.
As you know, in Windows it's possible to snap an app to the borders of the screen (as you can see in this video: https://www.youtube.com/watch?v=SB2dXXiueBw).

However, this function does not work with TVTest.

I ran some debugging on the code, and found that this is caused by TVTest programmatically managing the window drag in MainWindow.cpp (via events WM_NCLBUTTONDOWN+WM_LBUTTONDOWN+WM_NCLBUTTONUP+WM_LBUTTONUP+WM_CAPTURECHANGED+WM_MOUSEMOVE).
If I remove those events from MainWindow.cpp, then TVTest snap works fine.

However, I am unsure whether this change do not have any bad side effects.

Is it possible to improve this?

Thanks in advance,

Gaston

**Comment by gdassieu** [comment]
To add a bit more information to the issue.

When another application (example: notepad.exe) is resized by the user, below events are sent:
- 1 event 0x000A EVENT_SYSTEM_MOVESIZESTART
- several events 0x800B EVENT_OBJECT_LOCATIONCHANGE
- 1 event 0x000B EVENT_SYSTEM_MOVESIZEEND

However, when TVTest is resized, only below is sent:
- several events 0x800B EVENT_OBJECT_LOCATIONCHANGE
(no events 0x800A and 0x800B are received).

I think Windows needs 0x000A and 0x000B to manage the snapping.

Best,

Gaston

**Comment by gdassieu** [comment]
Hello,

I believe I have managed to fix the issue with Windows snap, without any negative impact on TVTest border snap and window move by clicking on TV area.

Attached is the updated MainWindow.cpp file with the corrections.
[MainWindow.cpp.zip](https://github.com/DBCTRADO/TVTest/files/4573702/MainWindow.cpp.zip)

Summary of the changes:

1. Instead of managing window move using WM_MOUSEMOVE message (OnMouseMove function), we will manage it using the WM_MOVING message. The adjusted position (after border snapping) is returned using the WM_MOVING lParam (as described in Microsoft doc https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-moving). After this change, the window move sends the right events to the OS (EVENT_SYSTEM_MOVESIZESTART -> EVENT_OBJECT_LOCATIONCHANGE -> EVENT_SYSTEM_MOVESIZEEND) and Windows snap functions correctly.

2. Side effect of previous change -> We can no longer drag the TVTest window by clicking on the TV area. To solve this, used the WM_LBUTTONDOWN message handler to re-send the click message as if it occurred in the title area (HTCAPTION). This is then used automatically to move the window.

Obviously, as I am not a member of TVTest development team, there's a chance these changes bring some regression. Anyway, I am fully available to help with testing and corrections if needed. Just let me know.

Cheers,

Gaston

**Comment by DBCTRADO** [comment]
Hello, Thank you for your report.
I'll try testing your patch.

**Comment by DBCTRADO** [comment]
I committed fix.

**Comment by DBCTRADO** [comment]
Fixed behavior with 7aa8065e777fcec04e8caa039554e7d0230530f8

**Comment by gdassieu** [comment]
Hi,
Thanks! I recompiled from the latest GIT repo, and I confirm it works well.
Best regards,
Gaston
