### ISSUE TITLE
パン&スキャン有効時に画面キャプチャがズレる

### ISSUE THREAD

**Issue by a1lic** [DBCTRADO/TVTest#52]
表記の件の不具合を確認しています。
パン&スキャンを使用して画面の一部を表示している状態でキャプチャを実行すると、保存される画像にズレが発生しました。
1枚目が、パン&スキャン有効時のTVTestでの画面で、2枚目がその状態でキャプチャを実行して生成された画像です。

![temp](https://user-images.githubusercontent.com/4565500/95660427-ce410400-0b62-11eb-8241-5b5389813be0.png)

![Capture20201011-013956](https://user-images.githubusercontent.com/4565500/95660430-d39e4e80-0b62-11eb-88d0-d2ffd45d2058.jpg)

普段の使用で、EVRで再生、キャプチャの大きさを表示されている大きさにしています。
レンダラでVMR9を使用時はEVRとは違った位置でズレます。

**Comment by DBCTRADO** [comment]
EVR は修正しました。
VMR9 は現象を確認できませんでした。

**Comment by a1lic** [comment]
返事が遅くなりすみません。
当方でも指定した通りにキャプチャが行えたことを確認しました。
遅くなってしまいましたが、対応ありがとうございます。
