### ISSUE TITLE
同名の音声デバイスが複数存在する環境で、音声デバイスの選択が正常に行えない

### ISSUE THREAD

**Issue by Maico-Tita** [DBCTRADO/TVTest#55]
タイトルの通りですが、同名の音声デバイスが複数存在する場合(画像中ではFG2421)、どちらを選んでも特定の側が常に選択されてしまいます。
![2021-08-07](https://user-images.githubusercontent.com/88556301/128554365-bdd73a4b-de3f-4ae3-ae03-1bb483a2436b.png)

**Comment by DBCTRADO** [comment]
恐らくモニカーでデバイスを同定すれば良いと思われますので、試してみます。

**Comment by DBCTRADO** [comment]
モニカー名でデバイス選択を行うようにしました。

**Comment by Maico-Tita** [comment]
早速の対応ありがとうございます。同名音声デバイス間の変更が可能になったのを確認しました。

更新が影響したのかは不明なのですが、この版から音声フィルタ(TvtAudioStretchFilter.ax等)が指定できなくなりました。
自分の環境がおかしい可能性もあると思いますので、引き続き確認してみます。

**Comment by DBCTRADO** [comment]
修正しました。

**Comment by Maico-Tita** [comment]
修正確認できました。
早速の対応ありがとうございます。
