### ISSUE TITLE
Alder Lake-S UHD 770でDXVA2によるデコードを有効にすると映像崩れが起こる

### ISSUE THREAD

**Issue by pikesaury** [DBCTRADO/TVTest#58]
お世話になります。記載の通りUHD [770とDXVA2によるデコードの組み合わせ（EVR)において、BS放送のみ添付画像のような映像乱れが頻繁に発生します（発生頻度は4-5秒に1回)。地デジ、CSでは発生はしないようです。
今のところわかっている事として録画についてはこのようなデータ状態にはなっていないので描画上の問題だけのようです。
EVR以外でもmadVRにしても同様に問題が発生するため、UHD770+ハードウエアデコードの処理の組み合わせにおいて、BSのみなんらかの理由で問題が発生するように思われます。こちらにつき原因特定は可能でしょうか。なお、外付けのGPU(nVIDIA)を装着した場合は当然の事ながら問題は発生いたしません。ご確認のほどよろしくお願いします。
![000](https://user-images.githubusercontent.com/37852075/161497348-16491012-e467-4ac5-8faa-2e858cce8624.png)]

**Comment by pikesaury** [comment]
お世話になります。追記となります。先日CSの無料放送をテストで流していた所、BS程ではありませんが一瞬映像乱れがありました。BSと地デジ/CSでの違いがわかっておりませんが、実際には地デジ/CSでも発生する（但し当方では超短時間のためきがつかない）症状かもしれません。どうぞよろしくおねがいします。

**Comment by DBCTRADO** [comment]
デコーダは何をお使いでしょうか。また、他のデコーダで DXVA2 を使った場合はどうでしょうか。
特定のデコーダのみで現象が発生するのであれば、そのデコーダの不具合の可能性が、複数のデコーダで同様に現象が発生するのであれば、ハードウェアやデバイスドライバの問題の可能性が考えられると思います。

**Comment by pikesaury** [comment]
ご返信ありがとうございます。上記の画像はTvTest DTV Decoderでした。その後MPC Video Decoderも試しましたが同じ症状が発生しLAV Video DecoderもDXVA2(copy backもnativeも駄目)にすると不具合がでてしまいました。
但しLAV Video DecoderはD3D11でもハードウエア処理ができるようで、D3D11で内蔵GPUを使ってみた所不具合は止まりました。ハードウエア処理でこの状態が1番安定しているようなので、当面これで使おうと思います。
以後はあくまでもご相談レベルですが、TvTest DTV Decoderはとても使いやすく便利なのですが、LAV Video DecoderでいうところのD3D11に対応をご検討いただけますととても助かります。インストール不要で環境の持ち運びができとても重宝しておりました。

**Comment by DBCTRADO** [comment]
D3D11 でのデコードは、まだあまり調べていないので実現できるか分かりませんが、とりあえず issue は立てておきました。

https://github.com/DBCTRADO/TVTestVideoDecoder/issues/4

**Comment by pikesaury** [comment]
検討に挙げていただきありがとうございます。調べてみたところ他のソフトですがMPC-BEなどでもAlderLaksで不具合がおこっているようなので、コア分離構造かUHD770の弊害のようです。このトピックはCloseとさせていただきます！
