### ISSUE TITLE
MESSAGE_GETSERVICEINFOで音声PIDを5つ以上取得できない

### ISSUE THREAD

**Issue by otya128** [DBCTRADO/TVTest#63]
地上波では1サービス/コンポーネントグループごとにPCR含めて16ESまで含むことが出来ますが、(TR-B14 第二分冊 2.1.2.5 ES数の制約, TR-B15 第一分冊 5.1.2.5 ES 数の制約)現在の実装ではAudioPID、AudioComponentTypeの配列長が4となっていてさらに範囲チェックがないため範囲外アクセスが発生する可能性があります。
https://github.com/DBCTRADO/TVTest/blob/1dbc22443edbdb5edd65e1e055ead0af20597830/src/Plugin.cpp#L1303-L1305

5以上の音声ESはコンポーネント0x10～0x2F外の普通の受信機では切り替え出来ないデータ放送用の音声ストリームで運用されていると思われます。 (https://www.ccn-catv.co.jp/ch/data/radio.html https://www.himawari.co.jp/news/info/ct995/ https://www.starcat.co.jp/cat-ch/method/radio/ https://wpub.people-i.ne.jp/web/news/radio_sousa.php などを参照)

コンポーネントグループを考慮しない場合AudioPID、AudioComponentTypeの配列長は15以上である必要があり、新たなメッセージを追加するか構造体を拡張の必要があるというのとPIDに加えてコンポーネントタグも取得出来たらプラグイン的に便利なので検討をお願いします。

**Comment by DBCTRADO** [comment]
プラグイン機能が実装された当時、そもそも音声ストリームの切り替え機能自体が存在していなかったので、その辺は適当になっていました。
情報を取得できるようなメッセージを追加したいと思います。

> 5以上の音声ESはコンポーネント0x10～0x2F外の普通の受信機では切り替え出来ないデータ放送用の音声ストリームで運用されていると思われます。

そういえば J:COMテレビで AM ラジオが聴けるようになっていましたね。
component_tag は 0x70〜 となっていました。

**Comment by DBCTRADO** [comment]
修正とメッセージの追加を行いました。
9dc083a8b6698dcca7fda66552c948c8a480e684
549d4ebff53ec559f98ebf86953445526370e13d

**Comment by xtne6f** [comment]
この更新によって字幕とともに文字スーパーの情報もとれるようになると思われるのでありがたいです。
便乗したいのですが、MESSAGE_GETSERVICEINFOの情報元となったPMT自体のPIDを (たとえばServiceInfoのReservedに含めるなどして) 取得できないでしょうか？
PCRのPIDをはじめマニアックな情報をとりたい状況が結構あって、そういうときはストリームコールバックでPMTそのものを捕捉することになるのですが、今のところ
(PATから全PMTのPIDを抽出)→(各PMTからVideoPIDなどを抽出)→(MESSAGE_GETSERVICEINFOのVideoPIDなどと比較)
というやや複雑な手順で現在選択中のサービスのPMTを特定しています。

※PATを解析する手間が要るか要らないか程度のアドバンテージなので、もし拡張が容易ならで構いません。ご検討ください。

**Comment by DBCTRADO** [comment]
情報取得系に機能不足な感はありますね。
ServiceInfo が既に汚い感じになっているのと、MESSAGE_GETSERVICEINFO では視聴可能なサービスの情報しか取得できないという点から、新しくメッセージを作る方がいいかと思っています。

**Comment by DBCTRADO** [comment]
80c1a1482ee0b9b1ac6ea24dba792da601d55a86 でサービスの情報を取得するための新しいメッセージを追加しました。
不足などありましたら教えてください。

**Comment by xtne6f** [comment]
ありがとうございます。新しいメッセージについて以下のように理解しました。

`MESSAGE_GETSERVICE`: 現在のストリームの視聴可能なサービスの数と視聴中のインデックスを取得
`MESSAGE_GETSERVICEINFO`: 現在のストリームの視聴可能なサービスの中から、特定サービス(インデックスで指定)の主要な情報を取得

(以下新しいメッセージ)

`MESSAGE_GETELEMENTARYSTREAMINFOLIST`: 現在のストリームの全サービスの中から、特定サービス(ServiceIDで指定)に含まれるメディア(ES)の情報を取得
`MESSAGE_GETSERVICECOUNT`: 現在のストリームの全サービスのサービス数を取得
`MESSAGE_GETSERVICEINFO2`: 現在のストリームの全サービスの中から、特定サービス(ServiceIDまたは全サービス中のインデックスで指定)の情報を取得
`MESSAGE_GETSERVICEINFOLIST`: 現在のストリームの全サービスまたは視聴可能なサービスの情報を全取得

.

`MESSAGE_GETSERVICEINFO2`について、視聴中のサービスを対象にしたい場合の手順がまどろっこしいのではないかと思いました。`MESSAGE_GETSERVICE`の戻り値はインデックスの意味がちがうので使えないはずで、たとえば`MESSAGE_GETELEMENTARYSTREAMINFOLIST`にある`ServiceID==0`の特別扱いがここにも欲しい気がします。

CTVTestAppのメソッドのほうにも戻り値の構造体に要解放フィールドが存在する旨、かるくコメントがあるとよいかも。
(構造体をRAIIなクラスで包む手もありますが、いくぶん複雑になるのでそこまでしなくてもいいかな)

**Comment by DBCTRADO** [comment]
各メッセージの理解については書かれました通りです。

`MESSAGE_GETSERVICEINFO2` で引数の `Service` を視聴可能なサービスの中でのインデックスと解釈するフラグを作りましょうか。
それと `Service` が -1 で現在のサービスの情報を取得、という感じで。

> CTVTestAppのメソッドのほうにも戻り値の構造体に要解放フィールドが存在する旨、かるくコメントがあるとよいかも。
> (構造体をRAIIなクラスで包む手もありますが、いくぶん複雑になるのでそこまでしなくてもいいかな)

コメントは付けておきます。
(ラッパーはあってもいいとは思いますが、サービス関係以外も含めて必要なものを全て用意するとそれなりに大変ですね…)

**Comment by otya128** [comment]
対応ありがとうございます。

情報取得系で言うと`MESSAGE_GETSTEREOMODE`でステレオモードは取れてもデュアルモノが再生中かは取れないのでEIT以外から取得できるAPIが欲しいです。

`MESSAGE_GETSTEREOMODE`に関してもステレオ音声のとき`STEREOMODE_LEFT`が返ってきてそれを`MESSAGE_SETSTEREOMODE`するとStereo(L)になり、その状態でも`MESSAGE_GETSTEREOMODE`は`STEREOMODE_LEFT`を返すというような微妙な状態になっているので現状デュアルモノ状態を取れないと危ういみたいな感じになっています。

**Comment by DBCTRADO** [comment]
途中で音声関係の実装を変更したため、`MESSAGE_GETSTEREOMODE` と `MESSAGE_SETSTEREOMODE` の挙動が当初の仕様とは変わってしまったのが混乱の元になってしまいました。
現状の仕様として、`MESSAGE_GETSTEREOMODE` で取得されるのは「デュアルモノラル時にどう再生されるか」で、`MESSAGE_SETSTEREOMODE` で指定すると「デュアルモノラル時にどう再生されるか + 現在ステレオであればそれにも反映させる」となっています。

この2つのメッセージは互換性のために残っているような存在なので、現状に合わせたメッセージを作りたいところです。音声情報の取得もできた方がいいですね。

**Comment by DBCTRADO** [comment]
`MESSAGE_GETSERVICEINFO2` での視聴可能なサービスの中でのインデックス指定と、現在のサービスの情報を簡単に取得できるようにしました。 b7e9bb46182438e88b2a72c356923ecf58a40c6b

音声の情報を取得できるようにしました。 7b605bef2444883f2d219dca78839978cddb4304

`MESSAGE_GETSTEREOMODE` と `MESSAGE_SETSTEREOMODE` の仕様の見直しや代替メッセージに関してはちょっと考えます。

**Comment by xtne6f** [comment]
サンプルのTSInfoプラグインを弄って新しいメッセージについて色々試したところ、問題なさそうです。
一貫性のため `GetLogo (DeleteObject)` と `FormatVarString (MemoryFree)` にも注釈が欲しいと思いました。

新しいメッセージは例えばこのように使うことになりますが
```cpp
TVTest::ElementaryStreamInfoList ESInfoList;
ESInfoList.Media = TVTest::ES_MEDIA_VIDEO; //★
ESInfoList.Flags = 0; //★
ESInfoList.ServiceID = ServiceInfo.ServiceID; //★
if (m_pApp->GetElementaryStreamInfoList(&ESInfoList)) {
	if (ESInfoList.ESCount)
		::wsprintf(szText, TEXT("%#x"), ESInfoList.ESList[0].PID);
	m_pApp->MemoryFree(ESInfoList.ESList);
}
```
★のところが若干煩わしいです(忘れやすいのと、引数が入出力の両方を兼ねているため)。可能ならこう書きたいです。
```cpp
if (m_pApp->GetElementaryStreamInfoList(&ESInfoList, TVTest::ES_MEDIA_VIDEO, ServiceInfo.ServiceID)) {
```
TVTestPlugin.h
```diff
-	bool GetElementaryStreamInfoList(ElementaryStreamInfoList *pList)
+	bool GetElementaryStreamInfoList(ElementaryStreamInfoList *pList, ElementaryStreamMediaType Media, WORD ServiceID)
 	{
 		pList->Size = sizeof(ElementaryStreamInfoList);
+		pList->Media = Media;
+		pList->Flags = 0;
+		pList->ServiceID = ServiceID;
 		return MsgGetElementaryStreamInfoList(m_pParam, pList);
@@
-	bool GetServiceInfo2(int Service, ServiceInfo2 *pInfo)
+	bool GetServiceInfo2(int Service, ServiceInfo2 *pInfo, DWORD ServiceInfo2Flags)
 	{
 		pInfo->Size = sizeof(ServiceInfo2);
+		pInfo->Flags = ServiceInfo2Flags;
 		return MsgGetServiceInfo2(m_pParam, Service, pInfo);
@@
-	bool GetServiceInfoList(ServiceInfoList *pList)
+	bool GetServiceInfoList(ServiceInfoList *pList, DWORD ServiceInfoListFlags)
 	{
 		pList->Size = sizeof(ServiceInfoList);
+		pList->Flags = ServiceInfoListFlags;
 		return MsgGetServiceInfoList(m_pParam, pList);
```

**Comment by DBCTRADO** [comment]
> 一貫性のため GetLogo (DeleteObject) と FormatVarString (MemoryFree) にも注釈が欲しいと思いました。

e460f6cf0ecca1a20434cc136f4580a75eb8df84 で追記しました。

> ★のところが若干煩わしいです(忘れやすいのと、引数が入出力の両方を兼ねているため)。可能ならこう書きたいです。 

これは全体的に言えることですね。一部は簡便に使えるようオーバーロードを定義してはいますが。
オーバーロードで提示されたような関数を追加したいと思います。

初期化忘れを防ぐという点では、いっそメンバに初期値を割り当てるのもありかという気がしました。

```C++
struct ServiceInfoList
{
	DWORD Size = sizeof(ServiceInfoList);
	DWORD Flags = 0;
	DWORD Reserved = 0;
	DWORD ServiceCount = 0;
	ServiceInfo2 *ServiceList = nullptr;
};
```

あまり記憶に無かったのですが、`RecordStatusInfo` だけは追加メンバに初期値を割り当てていますね。

**Comment by xtne6f** [comment]
ありがとうございます。今のもので問題なさそうです。
`MESSAGE_GETELEMENTARYSTREAMCOUNT` も正しく動作しているように思います。
`RecordStatusInfo` は今から動作を変えられるのかというのもありますし、個別の事情としてそれでいいと思います。

(蛇足: 細かいこと言えばフィールド未設定のほうのオーバーロードいらないかなぁ…派です。両方ないとできないこと特に無いですし必須フィールドの設定を強制できる、設定しなければコンパイルできないことが少なからず利点だからです。
しかし`MsgGet*()`との対称性だったり、初期化にも色々流儀があるとも思うので、個人的な感想です。)

**Comment by DBCTRADO** [comment]
b5d99a5bf41c4dc573a63ffe7c9fba9e17a96616 で音声選択の仕様を変更しました。
複雑さの元凶となっていた、(デュアルモノでない)ステレオ時に左右どちらかのみにする機能を削除しました。
`MESSAGE_SETSTEREOMODE` はデュアルモノに対してのみ効果を与えるようになりました。

また、 ead3f138fb1809318ecf6573b1d6005571d75140 で音声選択用のメッセージとして新しく `MESSAGE_SELECTAUDIO` を追加しました。

**Comment by otya128** [comment]
対応ありがとうございます。コンポーネントタグで選択できるのはかなり有用です。
見る限りMESSAGE_GETSERVICEINFO2で返ってくるTransportStreamIDとNetworkIDが逆のようです。
