### ISSUE TITLE
EVENT_PROGRAMGUIDE_COMMAND をプラグイン無効時にも受け取りたい

### ISSUE THREAD

**Issue by xtne6f** [DBCTRADO/TVTest#73]
TVTestのイベントは原則としてプラグインの有効状態 (`IsPluginEnabled()`) に関係なく受け取り、有効・無効らしく振るまう責任はプラグイン側にあると理解しますが、おそらく唯一 `EVENT_PROGRAMGUIDE_COMMAND` (番組の左ダブルクリック動作) だけはプラグイン有効時にかぎって受け取れるようです。
ふつうこれで支障ないのですが、あるプラグインが無効のとき、(そのプラグインの内部実装として) その番組表コマンドを処理できる別の有効なプラグインにそのコマンドを転送したいとき、この仕様が障害になります。

現状を変更するのはおそらく互換の問題があるので (たとえば EDCB Support Plugin というプラグインは無効時にこのコマンドが来ないことを前提にコーディングされているよう) 例えば `MESSAGE_ENABLEPROGRAMGUIDEEVENT` のフラグとして `EVENT_PROGRAMGUIDE_COMMAND` が常に受け取れるようになるフラグを設けることはできないでしょうか。

// 具体的には、TTRecにおいて「番組の左ダブルクリック動作」で予約登録などをする機能があり、
// かつ、BonDriverの種類に応じて複数のTTRecを利用できる (ただし有効にできるのはTVTest上で唯一) ため、
// あるTTRecへの「番組の左ダブルクリック動作」を有効状態のTTRecに転送したいです。

**Comment by DBCTRADO** [comment]
コマンドのイベントを常に送るフラグ `PROGRAMGUIDE_EVENT_COMMAND_ALWAYS` を追加しました。

**Comment by xtne6f** [comment]
ありがとうございます。目的の実装ができることをTTRecで確認しました。

追加されたフラグがない場合 `/inikey [ProgramGuide]ProgramLDoubleClick=...` の起動オプションで個別になんとかするアドホックな対処法が一応あるのですが、これ以外の作戦だと番組表コマンドを受け取るためだけのプラグインを新たに作るか、TTRecの仕様を大きく変えるかしかなかったので、とても助かります。
