### ISSUE TITLE
設定ウィンドウにて、リストビューのツールチップがウィンドウの裏側に表示される

### ISSUE THREAD

**Issue by noriokun4649** [DBCTRADO/TVTest#74]
設定ウィンドウのサイドバー、チャンネルスキャンなどで表示しきれないアイテムをマウスホバーした際に該当現象が確認できました。
可能であれば、修正お願い致します。

参考画像
![image](https://user-images.githubusercontent.com/17977166/190850168-62b182dd-e15e-4bd3-83ba-19fb54f413b6.png)
![image](https://user-images.githubusercontent.com/17977166/190850223-7dab9eac-871c-46a4-b5de-c7eafc89d482.png)

環境
OS : Windows 11 Pro 21H2
Version : TvTest 0.10.0-dev
Visual Studio 2022
MSVC: 19.32.31329.0
Commit : f98533ab7b07dc14435ccead288563a659cdfcce

**Comment by DBCTRADO** [comment]
「常に前面に表示」の状態でそのような現象が発生しますね。
ダイアログを表示する際に、一時的に前面表示を解除するよう対策を取るのが良いかと思いました。

試しにタスクマネージャーを調べたところ、「常に手前に表示」ではツールチップを無効にしていました(`LVS_EX_LABELTIP` スタイルが外れる)。
前面表示とツールチップの相性の悪さは、Microsoft も諦めている模様。

**Comment by noriokun4649** [comment]
原因特定有り難うございます。
「常に前面に表示」を無効にしたところ、該当の症状が解消されることを確認しました。

にしても、タスクマネージャでも解消されないことを、考えると根本的な解決は無理そうですね。
設定時に一時的に前面表示を解除するようにしたいと思います。

ありがとうございました。

**Comment by noriokun4649** [comment]
対応有り難うございます。
該当コミットをビルドして利用たところ、常に前面に表示を有効にした状態でも
リストビューのツールチップが前面に表示される事を確認しました。

有り難うございます。
