### ISSUE TITLE
音声フィルタの動作バグ

### ISSUE THREAD

**Issue by kouhgithub** [DBCTRADO/TVTest#75]
windows10 x64環境でtvtestの音声フィルターにMicrosoft ac3 encoderを設定しても動作しない

**Comment by DBCTRADO** [comment]
ドキュメントに Microsoft のアプリケーション以外からは使用できない旨の記載があるので、使えないとすれば仕様でしょう。

https://learn.microsoft.com/en-us/windows/win32/directshow/microsoft-ac3-encoder

> The Microsoft implementation of the Dolby Digital technology is restricted under terms of the Dolby Digital licensing program to use by Microsoft applications.

> This filter is not available for use by third-party applications.
